CREATE DATABASE ExamenPractic
GO
USE ExamenPractic
GO

CREATE TABLE CATEGORII
(
	ID INT PRIMARY KEY IDENTITY,
	DESCRIERE VARCHAR(100)
);

CREATE TABLE CREATORI
(
	ID INT PRIMARY KEY IDENTITY,
	NUME VARCHAR(50),
	ID_CATEGORIE INT FOREIGN KEY REFERENCES CATEGORII(ID)
);

CREATE TABLE PLATFORME
(
	ID INT PRIMARY KEY IDENTITY,
	NUME VARCHAR(50)
);

CREATE TABLE SERII
(
	ID INT PRIMARY KEY IDENTITY,
	NUME VARCHAR(50),
	ID_CREATOR INT FOREIGN KEY REFERENCES CREATORI(ID)
);

CREATE TABLE PROMOVARI
(
	ID_SERIE INT FOREIGN KEY REFERENCES SERII(ID),
	ID_PLATFORMA INT FOREIGN KEY REFERENCES PLATFORME(ID),
	ORA_START_PROMOVARE TIME,
	ORA_STOP_PROMOVARE TIME,
	CONSTRAINT PK_PROMOVARI PRIMARY KEY (ID_SERIE, ID_PLATFORMA)
);


CREATE OR ALTER PROCEDURE ADAUGA_PROMOVARE 
@ID_SERIE INT, 
@ID_PLATFORMA INT,
@ORA_START_PROMOVARE TIME,
@ORA_STOP_PROMOVARE TIME
AS
BEGIN

IF @ORA_STOP_PROMOVARE < @ORA_START_PROMOVARE
BEGIN
	RAISERROR('Orele precizate sunt invalide!', 16, 1);
	RETURN;
END

IF(EXISTS(SELECT 1 FROM PROMOVARI 
	WHERE ID_SERIE = @ID_SERIE 
	AND ID_PLATFORMA = @ID_PLATFORMA))
BEGIN
	UPDATE PROMOVARI SET ORA_START_PROMOVARE = @ORA_START_PROMOVARE, ORA_STOP_PROMOVARE = @ORA_STOP_PROMOVARE
	WHERE ID_SERIE = @ID_SERIE AND ID_PLATFORMA = @ID_PLATFORMA;
END

ELSE
BEGIN
	INSERT INTO PROMOVARI (ID_SERIE, ID_PLATFORMA, ORA_START_PROMOVARE, ORA_STOP_PROMOVARE)
	VALUES (@ID_SERIE, @ID_PLATFORMA, @ORA_START_PROMOVARE, @ORA_STOP_PROMOVARE);
END

END;


CREATE OR ALTER VIEW VW_SERII AS
SELECT NUME FROM SERII WHERE ID NOT IN
(SELECT S.ID FROM SERII S
INNER JOIN PROMOVARI PR ON PR.ID_SERIE = S.ID
WHERE EXISTS(SELECT ID FROM PLATFORME P WHERE P.ID NOT IN 
(SELECT ID_PLATFORMA FROM PROMOVARI PR WHERE PR.ID_SERIE = S.ID)))

CREATE OR ALTER VIEW VW_SERII_2 AS
SELECT DISTINCT S.NUME FROM SERII S
INNER JOIN PROMOVARI PR ON PR.ID_SERIE = S.ID
WHERE NOT EXISTS(SELECT ID FROM PLATFORME P WHERE P.ID NOT IN 
(SELECT ID_PLATFORMA FROM PROMOVARI PR WHERE PR.ID_SERIE = S.ID))


INSERT INTO CATEGORII(DESCRIERE) VALUES
('LIFESTYLE'), ('TRAVEL'), ('GAMING'), ('FASHION');

INSERT INTO CREATORI(NUME, ID_CATEGORIE) VALUES
('MRBEAST', 1), ('PEWDIEPIE', 3), ('CASEY NEISTAT', 2);

INSERT INTO PLATFORME(NUME) VALUES
('INSTAGRAM'), ('TIKTOK'), ('YOUTUBE');

INSERT INTO SERII(NUME, ID_CREATOR) VALUES
('DAM BANI LA SARACI', 1), ('GAMING SESSIONS', 2), ('TRAVEL THE GLOBE', 3);

INSERT INTO PROMOVARI(ID_SERIE, ID_PLATFORMA, ORA_START_PROMOVARE, ORA_STOP_PROMOVARE) VALUES
(1, 1, '13:30:00', '13:40:00'), (1, 2, '13:30:00', '13:45:00'), (1, 3, '13:50:00', '14:00:00'),
(2, 1, '10:20:00', '10:35:00'), (2, 3, '10:15:00', '10:20:00'),
(3, 2, '16:45:00', '17:00:00');

EXEC ADAUGA_PROMOVARE 2, 2, '20:30', '20:50';
SELECT * FROM PROMOVARI;

DELETE FROM PROMOVARI WHERE ID_SERIE = 2 AND ID_PLATFORMA = 2;
SELECT * FROM VW_SERII;
SELECT * FROM VW_SERII_2;