--USE master;
--GO
--ALTER DATABASE model SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
--GO
--ALTER DATABASE model SET MULTI_USER;
--GO

CREATE DATABASE ModelTable;
GO
USE ModelTable;
GO

CREATE TABLE ANGAJATI
(
	ID INT PRIMARY KEY IDENTITY,
	NUME VARCHAR(50),
	NR_CONTRACT VARCHAR(50)
);

CREATE TABLE MESE
(
	ID INT PRIMARY KEY IDENTITY,
	NUMAR INT,
	CULOARE VARCHAR(50)
);

CREATE TABLE MECIURI
(
	ID INT PRIMARY KEY IDENTITY,
	DATA_MECI DATE,
	ID_MASA INT FOREIGN KEY REFERENCES MESE(ID),
	ID_P1 INT FOREIGN KEY REFERENCES ANGAJATI(ID),
	ID_P2 INT FOREIGN KEY REFERENCES ANGAJATI(ID),
	ID_CASTIGATOR INT FOREIGN KEY REFERENCES ANGAJATI(ID),
);

CREATE TABLE MUTARI
(
	ID INT PRIMARY KEY IDENTITY,
	ID_JUCATOR INT FOREIGN KEY REFERENCES ANGAJATI(ID),
	ID_MECI INT FOREIGN KEY REFERENCES MECIURI(ID),
	ZAR1 INT CHECK (ZAR1 BETWEEN 1 AND 6),
	ZAR2 INT CHECK (ZAR2 BETWEEN 1 AND 6),
	PIESA_MUTATA_DE_LA VARCHAR(10),
	PIESA_MUTATA_LA VARCHAR(10)
);

CREATE TABLE SPECTATORI
(
	ID_ANGAJAT INT FOREIGN KEY REFERENCES ANGAJATI(ID),
	ID_MECI INT FOREIGN KEY REFERENCES MECIURI(ID),
	CONSTRAINT PK_SPECTATORI PRIMARY KEY (ID_ANGAJAT, ID_MECI)
);

CREATE OR ALTER PROCEDURE CalculeazaPremiu @id_participant INT
AS
BEGIN

DECLARE @nr_castigate INT;
SELECT @nr_castigate = COUNT(*) FROM MECIURI
WHERE ID_CASTIGATOR = @id_participant;

DECLARE @nr_spectatori INT;
SELECT @nr_spectatori = COUNT(*) FROM SPECTATORI S
INNER JOIN MECIURI M ON M.ID = S.ID_MECI
WHERE M.ID_P1 = @id_participant OR M.ID_P2 = @id_participant;

DECLARE @nr_meciuri_spectator INT;
SELECT @nr_meciuri_spectator = COUNT(*) FROM SPECTATORI
WHERE ID_ANGAJAT = @id_participant;

DECLARE @nr_meciuri_participant INT;
SELECT @nr_meciuri_participant = COUNT(*) FROM MECIURI
WHERE @id_participant IN (ID_P1, ID_P2);

DECLARE @total_meciuri INT;
SELECT @total_meciuri = COUNT(*) FROM MECIURI;

DECLARE @premiu INT;
SET @premiu = 100 * @nr_castigate 
			+ 10 * @nr_spectatori 
			- 10 * (@total_meciuri - (@nr_meciuri_participant + @nr_meciuri_spectator));
IF @premiu < 0
	RETURN  0;

RETURN @premiu;

END;


CREATE VIEW vw_duble AS
SELECT COUNT(*) AS 'Numar duble' FROM MUTARI MU
INNER JOIN ANGAJATI A ON A.ID = MU.ID_JUCATOR
WHERE A.NR_CONTRACT LIKE 'CLF3215'
AND MU.ZAR1 = MU.ZAR2;

INSERT INTO ANGAJATI (NUME, NR_CONTRACT) VALUES
('BOGDAN IOAN', 'CLF3215'),
('IOAN URSU', 'CLF2254'),
('NICOLAE IORGA', 'CLF2134'),
('AXENTE SEVER', 'CLF0023'),
('EMIL RACOVITA', 'CLF0213')

INSERT INTO MECIURI (DATA_MECI, ID_P1, ID_P2, ID_CASTIGATOR) VALUES
(GETDATE(), 1,2, 1),
(GETDATE(), 1,3, 1),
(GETDATE(), 1,4, 1),
(GETDATE(), 1,5, 5),
(GETDATE(), 2,3, 2)

INSERT INTO SPECTATORI (ID_MECI, ID_ANGAJAT) VALUES
(1, 3), (1,4), (1,5),
(2,2), (2,5),
(3,2), (3,3), (3,5),
(4,2), (4,3), (4,4)

INSERT INTO MUTARI (ID_JUCATOR, ID_MECI, ZAR1, ZAR2, PIESA_MUTATA_DE_LA, PIESA_MUTATA_LA) VALUES
(1,1,5,5, '1-2', '2-3'),
(2,1,5,5, '1-2', '2-3'),
(1,2,4,4, '1-2', '2-3'),
(3,5,5,5, '1-2', '2-3'),
(1,3,3,4, '1-2', '2-3')

SELECT * FROM vw_duble;

DECLARE @premiu INT;
EXEC @premiu = CalculeazaPremiu 1;
SELECT @premiu;