CREATE DATABASE ModelAlegeri
GO
USE ModelAlegeri
GO

CREATE TABLE SECTII
(
	ID INT PRIMARY KEY IDENTITY,
	NUMAR INT
);

CREATE TABLE CETATENI
(
	ID INT PRIMARY KEY IDENTITY,
	NUME VARCHAR(50),
	PRENUME VARCHAR(50),
	CNP VARCHAR(20),
	ID_SECTIE INT FOREIGN KEY REFERENCES SECTII(ID)
);

CREATE TABLE CANDIDATI
(
	ID INT PRIMARY KEY IDENTITY,
	NUME VARCHAR(50),
	PRENUME VARCHAR(50),
	DATA_NASTERII DATE
);

CREATE TABLE VOTURI
(
	ID INT PRIMARY KEY IDENTITY,
	ID_CETATEAN INT FOREIGN KEY REFERENCES CETATENI(ID),
	ID_SECTIE INT FOREIGN KEY REFERENCES SECTII(ID),
	ORA TIME,
	PE_LISTA_SUPLIMENTARA BIT,
	ID_CANDIDAT INT FOREIGN KEY REFERENCES CANDIDATI(ID)
);

CREATE TABLE ECHIPAJE
(
	ID INT PRIMARY KEY IDENTITY,
	NUMAR INT,
	NUMAR_MEMBRII INT
);

CREATE TABLE ECHIPAJE_SECTII
(
	ID_ECHIPAJ INT FOREIGN KEY REFERENCES ECHIPAJE(ID),
	ID_SECTIE INT FOREIGN KEY REFERENCES SECTII(ID),
	CONSTRAINT PK_ES PRIMARY KEY (ID_ECHIPAJ, ID_SECTIE)
);

/* CREATE OR ALTER PROCEDURE AflaCastigator @ID_SECTIE INT,
@ID_CASTIGATOR INT OUTPUT
AS
BEGIN

DECLARE @CANDIDAT_VOTURI TABLE (ID_CANDIDAT INT, NR_VOTURI INT);
INSERT INTO @CANDIDAT_VOTURI 
SELECT ID_CANDIDAT, COUNT(*) FROM VOTURI
GROUP BY ID_CANDIDAT;

DECLARE @MAX INT;
SELECT @MAX = MAX(NR_VOTURI) FROM @CANDIDAT_VOTURI
GROUP BY ID_CANDIDAT;

SELECT TOP 1 @ID_CASTIGATOR = ID_CANDIDAT FROM @CANDIDAT_VOTURI
WHERE NR_VOTURI = @MAX;

DECLARE @TOTAL INT;
SELECT @TOTAL = COUNT(*) FROM VOTURI;

DECLARE @PROCENT REAL;
SET @PROCENT = (@MAX * 100) / @TOTAL;

RETURN @PROCENT;

END; */

CREATE OR ALTER PROCEDURE AflaCastigator @ID_SECTIE INT,
@ID_CASTIGATOR INT OUTPUT
AS
BEGIN

DECLARE @MAX INT;

SELECT TOP 1 @ID_CASTIGATOR = V.ID_CANDIDAT, @MAX = V.TOTAL_VOTURI FROM
(SELECT ID_CANDIDAT, COUNT(*) AS TOTAL_VOTURI FROM VOTURI
WHERE ID_SECTIE = @ID_SECTIE
GROUP BY ID_CANDIDAT) V
ORDER BY V.ID_CANDIDAT;

DECLARE @TOTAL INT;
SELECT @TOTAL = COUNT(*) FROM VOTURI
WHERE ID_SECTIE = @ID_SECTIE;

DECLARE @PROCENT REAL;
SET @PROCENT = (@MAX * 100) / @TOTAL;

RETURN @PROCENT;

END;


CREATE OR ALTER VIEW VW_VOTURI_GEORGESCU AS 
SELECT CONVERT(VARCHAR(10),S.NUMAR) + ': ' + CONVERT(VARCHAR(10), COUNT(*)) AS [DATE] FROM VOTURI V
INNER JOIN CANDIDATI C ON V.ID_CANDIDAT = C.ID
INNER JOIN SECTII S ON V.ID_SECTIE= S.ID
WHERE C.PRENUME LIKE 'Calin' AND C.NUME = 'Georgescu'
GROUP BY V.ID_SECTIE, S.NUMAR
HAVING COUNT(*) > 500