CREATE DATABASE ModelCaleidoscop;
GO
USE ModelCaleidoscop;
GO

CREATE TABLE EPISOADE
(
	ID INT PRIMARY KEY IDENTITY,
	DURATA INT,		-- SECUNDE
	NUME VARCHAR(50),
	ORDINE INT CHECK (ORDINE BETWEEN 1 AND 9)
);

CREATE TABLE UTILIZATORI
(
	ID INT PRIMARY KEY IDENTITY,
	NUME VARCHAR(50),
	EMAIL NVARCHAR(50)
);

CREATE TABLE ACTORI
(
	ID INT PRIMARY KEY IDENTITY,
	NUME VARCHAR(50)
);

CREATE TABLE REPLICI
(
	ID INT PRIMARY KEY IDENTITY,
	TEXT NVARCHAR(100),
	TIMP_REPLICA INT,  -- SECUNDA IN EPISOD CAND E SPUSA
	ID_ACTOR INT FOREIGN KEY REFERENCES ACTORI(ID),
	ID_EPISOD INT FOREIGN KEY REFERENCES EPISOADE(ID)
);

CREATE TABLE EPISOADE_ACTORI
(
	ID_EPISOD INT FOREIGN KEY REFERENCES EPISOADE(ID),
	ID_ACTOR INT FOREIGN KEY REFERENCES ACTORI(ID),
	CONSTRAINT PK_EPISOADE_ACTORI PRIMARY KEY (ID_EPISOD, ID_ACTOR)
);

CREATE TABLE VIZIONARI
(
	ID_UTILIZATOR INT FOREIGN KEY REFERENCES UTILIZATORI(ID),
	ID_EPISOD INT FOREIGN KEY REFERENCES EPISOADE(ID),
	CONSTRAINT PK_VIZIONARI PRIMARY KEY (ID_UTILIZATOR, ID_EPISOD)
);


CREATE OR ALTER PROCEDURE PLAY_EPISOD @ID_UTILIZATOR INT
AS
BEGIN

DECLARE @EPISOADE_RAMASE TABLE (ID INT);
INSERT INTO @EPISOADE_RAMASE SELECT ID FROM EPISOADE
WHERE ID NOT IN 
(SELECT E.ID FROM EPISOADE E 
INNER JOIN VIZIONARI V ON V.ID_EPISOD = E.ID AND V.ID_UTILIZATOR = @ID_UTILIZATOR);

DECLARE @NR_RAMASE INT;
SELECT @NR_RAMASE = COUNT(*) FROM @EPISOADE_RAMASE;

DECLARE @ID_EPISOD INT;

IF @NR_RAMASE = 0
BEGIN
	RAISERROR('Nu mai sunt episoade de vizionat!', 16, 1);
	RETURN;
END

IF @NR_RAMASE = 1
	SET @ID_EPISOD = 9;
	-- SAU SELECT @ID_EPISOD = ID FROM @EPISOADE RAMASE; FIINDCA AVEM GARANTIA CA A RAMAS 9 ULTIMUL
ELSE
	SELECT TOP 1 @ID_EPISOD = ID FROM @EPISOADE_RAMASE
	WHERE ID <> 9
	ORDER BY RAND();

INSERT INTO VIZIONARI (ID_UTILIZATOR, ID_EPISOD) VALUES (@ID_UTILIZATOR, @ID_EPISOD);

END

-- ALTERNATIV DE PE GITHUB
/* CREATE OR ALTER PROCEDURE PLAY (@ID_UTILIZATOR INT) 
AS
BEGIN
	DECLARE @NR_EPISOADE_VIZIONATE INT
	SELECT @NR_EPISOADE_VIZIONATE = COUNT(*) FROM VIZIONARI
	WHERE ID_UTILIZATOR = @ID_UTILIZATOR
	
	IF @NR_EPISOADE_VIZIONATE = 9
		RETURN
	IF @NR_EPISOADE_VIZIONATE = 8
	BEGIN
		INSERT INTO VIZIONARI VALUES (@ID_UTILIZATOR, 9)
		RETURN
	END
	DECLARE @URMATORUL_EPISOD INT
	SET @URMATORUL_EPISOD = FLOOR(1 + RAND() * 8) -- genereaza un int in [1,8] 
	WHILE @URMATORUL_EPISOD <> 9 and 
		  EXISTS (SELECT 1 FROM VIZIONARI VIZ
				  INNER JOIN EPISOADE EPI ON VIZ.ID_EPISOD = EPI.ID
				  WHERE VIZ.ID_UTILIZATOR = @ID_UTILIZATOR
					AND EPI.ORDINE_CRONOLOGICA = @URMATORUL_EPISOD)
		SET @URMATORUL_EPISOD = FLOOR(1 + RAND() * 8)

	DECLARE @ID_URMATORUL_EPISOD INT
	SELECT @ID_URMATORUL_EPISOD = ID FROM EPISOADE WHERE ORDINE_CRONOLOGICA = @URMATORUL_EPISOD

	INSERT INTO VIZIONARI VALUES (@ID_UTILIZATOR, @ID_URMATORUL_EPISOD)
END */


SELECT A.NUME + ': ' + R.TEXT AS 'SCRIPT' FROM REPLICI R
INNER JOIN ACTORI A ON A.ID = R.ID_ACTOR
INNER JOIN EPISOADE E ON E.ID = R.ID_EPISOD
ORDER BY E.ORDINE, R.TIMP_REPLICA ASC;

INSERT INTO UTILIZATORI (NUME, EMAIL) VALUES 
('BOGDANEL_BD', 'BOGDANEL_BD@BDRULZ.COM'),
('DONALD', 'DDONALD@US.COM')

INSERT INTO ACTORI (NUME) VALUES
('PAZ VEGA'), ('TATI GABRIELLE'), ('GIANCARLO ESPOSITO')

INSERT INTO EPISOADE (DURATA, NUME, ORDINE) VALUES 
(25, 'BLACK', 1), (30, 'YELLOW', 2), (25, 'GREEN', 3), (30, 'BLUE', 4),
(25, 'ORANGE', 5), (30, 'VIOLET', 6), (25, 'RED', 7), (30, 'PINK', 8),
(40, 'WHITE: THE HEIST', 9)

INSERT INTO REPLICI (TEXT, TIMP_REPLICA, ID_ACTOR, ID_EPISOD) VALUES
('BUNA SEARA, STUDENT', 20, 3, 1),
('BUNA SEARA, DOMN PROFESOR', 1, 1, 1),
('5', 5, 3, 9),
('CE NOTA AM LA BAZE DE DATE?', 4, 1, 7),
('MULTUMESC!', 21, 1, 6)